#!/bin/bash
#**********************************************************
#* File:load-critcel-future-intel-modules.sh
#* 
#* Desc:Force the loading of future intel modules required by Critcel
#*      This 'clears' the existing modules
#*
#* Date:Sun 05 Jan 2014 
#*
#* Author: Kevin Manalo
#* Email:  kmanalo@gmail.com

# drop all current modules

if [ $# -eq 0 ] ; then
    echo usage: load-modules.sh run

else
    export LOADEDMODULES=""
    export _LMFILES_=""
    # git rev-parse --show-toplevel - see
    # http://stackoverflow.com/a/957978/992834
    toplevel=$(git rev-parse --show-toplevel)
    source $toplevel/hdf5-modules 
    # apparently this is not loading
    export PATH=$PATH:/usr/local/packages/mvapich2/1.9/intel-13.2.146/bin/

    echo The following modules are loaded for using Critcel:
    module list
fi
